import SwiftUI

struct StudioCommands: Commands {
    @FocusedValue(\.circuitEditor) private var store
    var body: some Commands {
        CommandGroup(after: .newItem) { Button("Circuit templates…") { store?.showTemplates = true }; Button("Import CircuitikZ…") { store?.showImport = true } }
        CommandGroup(replacing: .pasteboard) { Button("Copy") { if let store { StudioClipboard.copySelection(store) } }.keyboardShortcut("c").disabled(store?.selection.isEmpty ?? true); Button("Paste") { if let store { StudioClipboard.pasteSelection(store) } }.keyboardShortcut("v"); Button("Duplicate") { store?.duplicateSelection() }.keyboardShortcut("d").disabled(store?.selection.isEmpty ?? true); Button("Delete") { store?.deleteSelection() }.keyboardShortcut(.delete, modifiers: []).disabled(store?.selection.isEmpty ?? true); Divider(); Menu("Copy as") { ForEach(ExportFormat.allCases.filter { store?.supportsSimulation != false || $0 != .spice }) { format in Button(format.rawValue) { if let store { StudioClipboard.copyAs(format, store: store) } } } } }
        CommandMenu("Circuit") { Button("Add component…") { store?.paletteQuery = ""; store?.showPalette = true }.keyboardShortcut("a", modifiers: []); Button("Command palette…") { store?.paletteQuery = ""; store?.showPalette = true }.keyboardShortcut("p"); Divider(); Button("Rotate") { store?.transformSelection("Rotate") }.keyboardShortcut("r", modifiers: []); Button("Flip horizontal") { store?.transformSelection("Flip horizontal") }.keyboardShortcut("h", modifiers: []); Button("Flip vertical") { store?.transformSelection("Flip vertical") }.keyboardShortcut("v", modifiers: []); Divider(); Button("Clean up circuit") { store?.cleanUp() }; Button("Renumber circuit") { store?.renumber() }; Button("Select all") { if let store { store.selection = store.circuit.objectIDs } }.keyboardShortcut("a") }
        CommandMenu("Paper figure") { ForEach(FigureKind.allCases) { kind in Button(kind.rawValue) { store?.insertFigure(kind) } }; Button("Draw arrow") { store?.cancel(); store?.tool = .connector }.keyboardShortcut("l", modifiers: []); Divider(); Button("Align horizontally") { store?.align("horizontal") }; Button("Align vertically") { store?.align("vertical") }; Button("Distribute horizontally") { store?.distribute("horizontal") }; Button("Distribute vertically") { store?.distribute("vertical") }; Divider(); ForEach(PaperExample.allCases) { example in Button(example.rawValue) { store?.insertPaperExample(example) } } }
        CommandMenu("Canvas mode") { ForEach(CanvasPurpose.allCases) { purpose in Button(purpose.rawValue) { store?.setPurpose(purpose) }.disabled(store == nil) } }
        CommandMenu("Simulation") { Group { Button("Run simulation") { store?.runSimulation() }.keyboardShortcut(.return); Button("Configure analysis…") { store?.showSimulationSettings = true }; Button("Model library…") { store?.showModels = true }; Button("Show waveforms") { store?.showWaveforms.toggle() }.disabled(store?.simulationResult == nil); Button("Annotate operating points") { store?.annotateOP.toggle() }.disabled(store?.simulationResult?.analysis != .op) }.disabled(store?.supportsSimulation != true) }
        CommandGroup(after: .toolbar) { Button("Toggle grid") { store?.showGrid.toggle() }; Button("Snap to grid") { store?.snapEnabled.toggle() }; Button("Fit circuit") { store?.fit() }.keyboardShortcut("0"); Button("Zoom in") { if let store { store.changeZoom(store.zoom * 1.2) } }.keyboardShortcut("+"); Button("Zoom out") { if let store { store.changeZoom(store.zoom / 1.2) } }.keyboardShortcut("-") }
        CommandGroup(after: .importExport) { Button("Export circuit…") { store?.showExport = true }.keyboardShortcut("e", modifiers: [.command, .shift]) }
    }
}
