import Foundation

public enum SPICENetlist {
    public static func generate(_ circuit: Circuit, analysis: Bool = true) throws -> String {
        guard circuit.purpose.supportsSimulation else { throw CircuitError.message("Illustration documents do not run simulations. Switch to Schematic to generate a SPICE netlist.") }
        let topology = Connectivity(circuit)
        guard Set(circuit.components.filter { !$0.kind.isConnection }.map { $0.name.uppercased() }).count == circuit.components.filter({ !$0.kind.isConnection }).count else { throw CircuitError.message("Two components have the same name. Rename them before simulation.") }
        var lines = ["* \(circuit.title.replacingOccurrences(of: "\n", with: " "))", "* Generated by Circuit Studio"]
        for c in circuit.components where !c.kind.isConnection {
            guard c.name.range(of: #"^[A-Za-z][A-Za-z0-9_]*$"#, options: .regularExpression) != nil, c.name.uppercased().hasPrefix(c.kind.prefix) else { throw CircuitError.message("\(c.name) needs a valid \(c.kind.prefix) reference designator.") }
            func n(_ pin: String) -> String { topology.net(c.id, pin) }
            func v(_ key: String, _ fallback: String = "0") throws -> String { try EngineeringUnits.spice(c.parameters[key] ?? fallback) }
            let p = c.parameters
            switch c.kind {
            case .resistor, .capacitor, .polarizedCapacitor, .inductor:
                guard try EngineeringUnits.parse(p["value"] ?? "0") > 0 else { throw CircuitError.message("\(c.name) must have a positive value.") }
                lines.append("\(c.name) \(n("1")) \(n("2")) \(try v("value"))")
            case .voltageSource, .acVoltage, .pulseSource:
                var source = "\(c.name) \(n("1")) \(n("2")) DC \(try v("value")) AC \(try v("ac"))"
                if c.kind == .acVoltage { source += " SIN(\(try v("value")) \(try v("amplitude")) \(try v("frequency")))" }
                if c.kind == .pulseSource { source += " PULSE(\(try v("value")) \(try v("high")) 0 1n 1n \(try v("width")) \(try v("period")))" }
                lines.append(source)
            case .currentSource: lines.append("\(c.name) \(n("1")) \(n("2")) DC \(try v("value"))")
            case .nmos, .pmos:
                let model = try modelName(p["model"] ?? c.kind.rawValue)
                for key in ["W", "L", "M", "NF"] { guard try EngineeringUnits.parse(p[key] ?? "0") > 0 else { throw CircuitError.message("\(c.name): \(key) must be positive.") } }
                // Level-1 models have no NF instance parameter; represent fingers through M.
                let multiplier = try EngineeringUnits.parse(p["M"] ?? "1") * EngineeringUnits.parse(p["NF"] ?? "1")
                lines.append("\(c.name) \(n("D")) \(n("G")) \(n("S")) \(p["bulk"] == "external" ? n("B") : n("S")) \(model) W=\(try v("W")) L=\(try v("L")) M=\(multiplier)")
            case .npn, .pnp: lines.append("\(c.name) \(n("C")) \(n("B")) \(n("E")) \(try modelName(p["model"] ?? "NPN"))")
            case .diode, .zener, .led: lines.append("\(c.name) \(n("1")) \(n("2")) \(try modelName(p["model"] ?? "DDEFAULT"))")
            case .opAmp: lines.append("\(c.name) \(n("OUT")) 0 \(n("+")) \(n("-")) \(try v("gain", "100k"))")
            default: break
            }
        }
        let library = try validatedModels(circuit.modelLibrary)
        let defaults = ["NMOS": ".model NMOS NMOS (LEVEL=1 VTO=0.45 KP=120u LAMBDA=0.04)", "PMOS": ".model PMOS PMOS (LEVEL=1 VTO=-0.45 KP=60u LAMBDA=0.04)", "NPN": ".model NPN NPN (IS=1e-15 BF=100)", "PNP": ".model PNP PNP (IS=1e-15 BF=100)", "DDEFAULT": ".model DDEFAULT D (IS=1e-14 N=1)"]
        for key in defaults.keys.sorted() where library.range(of: "(?im)^\\s*\\.model\\s+\(key)\\s", options: .regularExpression) == nil { lines.append(defaults[key]!) }
        if !library.isEmpty { lines.append(library) }
        if analysis { lines.append(try directive(circuit.simulation)) }
        lines.append(".end"); return lines.joined(separator: "\n") + "\n"
    }
    public static func validate(_ circuit: Circuit) throws {
        guard !circuit.components.isEmpty else { throw CircuitError.message("Add components to the canvas before running a simulation.") }
        guard circuit.components.contains(where: { $0.kind == .ground }) else { throw CircuitError.message("Add a ground reference to your circuit.") }
        let topology = Connectivity(circuit)
        if let conflict = topology.conflictingLabels.first { throw CircuitError.message("Net labels \(conflict.joined(separator: ", ")) share the same wire. Rename or disconnect them.") }
        for net in topology.nets where net.name != "0" {
            let active = net.terminals.filter { ref in circuit.components.first { $0.id == ref.componentID }.map { !$0.kind.isConnection } ?? false }
            if active.count == 1 { throw CircuitError.message("Node \(net.name) is floating. Connect it to another component or a ground reference.") }
        }
        _ = try generate(circuit)
    }
    public static func directive(_ s: SimulationSettings) throws -> String {
        switch s.analysis {
        case .op: return ".op"
        case .ac:
            let start = try EngineeringUnits.parse(s.start), stop = try EngineeringUnits.parse(s.stop)
            guard start > 0, stop > start, s.points > 0, s.points <= 500 else { throw CircuitError.message("AC analysis needs a positive start frequency and a larger stop frequency.") }
            return ".ac dec \(s.points) \(start) \(stop)"
        case .dc:
            let start = try EngineeringUnits.parse(s.dcStart), stop = try EngineeringUnits.parse(s.dcStop), step = try EngineeringUnits.parse(s.dcStep)
            guard stop > start, step > 0, (stop - start) / step <= 100_000, s.source.range(of: #"^[VI][A-Za-z0-9_]+$"#, options: .regularExpression) != nil else { throw CircuitError.message("Check the DC source and sweep range; use at most 100,000 steps.") }
            return ".dc \(s.source) \(start) \(stop) \(step)"
        case .tran:
            let step = try EngineeringUnits.parse(s.timeStep), duration = try EngineeringUnits.parse(s.duration)
            guard step > 0, duration > step, duration / step <= 100_000 else { throw CircuitError.message("Transient analysis needs a positive time step and at most 100,000 steps.") }
            return ".tran \(step) \(duration)"
        }
    }
    static func modelName(_ text: String) throws -> String {
        guard text.range(of: #"^[A-Za-z][A-Za-z0-9_]*$"#, options: .regularExpression) != nil else { throw CircuitError.message("“\(text)” is not a valid SPICE model name.") }; return text
    }
    public static func validatedModels(_ library: String) throws -> String {
        for line in library.components(separatedBy: .newlines) {
            let line = line.trimmingCharacters(in: .whitespaces)
            if line.isEmpty || line.hasPrefix("*") || line.hasPrefix("+") || line.lowercased().hasPrefix(".model ") || line.lowercased().hasPrefix(".param ") { continue }
            throw CircuitError.message("Model libraries currently accept .model, .param and continuation lines. Flatten .lib / .include files before importing.")
        }
        return library
    }
}
